# composite actions

name: 'Get & Cache Dependencies'
description: 'Get dependencies and cache them'

runs:
  using: composite
  steps:
    - name: Cache dependencies
      run: echo "caching..."
      shell: bash
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: bash
